const  tasksData = [
    {
        id: 1,
        category: 'Образование',
        title: 'Подготовка к ЕГЭ',
        description: 'Помощь в подготовке к экзаменам по математике и физике.',
        tasker: 'Петрова',
        heashTags: ['ЕГЭ', 'математика', 'физика'],
        deadLineDate: '20231015',
        price: '5000',
        requiresApproval: false,
    },
    {
        id: 2,
        category: 'Спорт',
        title: 'Тренировка по футболу',
        description: 'Индивидуальная тренировка для начинающих футболистов.',
        tasker: 'Сидоров',
        heashTags: ['футбол', 'тренировка', 'спорт'],
        deadLineDate: '20230930',
        price: '2000',
        requiresApproval: true,
    },
    {
        id: 3,
        category: 'IT',
        title: 'Разработка сайта',
        description: 'Создание лендинга для малого бизнеса.',
        tasker: 'Козлов',
        heashTags: ['веб-разработка', 'лендинг', 'IT'],
        deadLineDate: '20231120',
        price: '15000',
        requiresApproval: true,
    },
    {
        id: 4,
        category: 'Искусство',
        title: 'Уроки рисования',
        description: 'Обучение основам акварельной живописи.',
        tasker: 'Иванова',
        heashTags: ['рисование', 'акварель', 'искусство'],
        deadLineDate: '20231010',
        price: '4000',
        requiresApproval: false,
    },
    {
        id: 5,
        category: 'Кулинария',
        title: 'Мастер-класс по выпечке',
        description: 'Приготовление домашнего хлеба и пирогов.',
        tasker: 'Смирнова',
        heashTags: ['кулинария', 'выпечка', 'хлеб'],
        deadLineDate: '20231025',
        price: '3500',
        requiresApproval: true,
    }
];